version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  assignees:
  - njuettner
  ignore:
  - dependency-name: github.com/sirupsen/logrus
    versions:
    - 1.7.1
